
import os

from genai import GenAI
GOOGLE_API_KEY = "AIzaSyCFZRAWFTx5a56l9qhe194ROa6xCfuVozw"
GOOGLE_APPLICATION_CREDENTIALS = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")
genai = GenAI(api_key=GOOGLE_APPLICATION_CREDENTIALS)